using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TeamRaiden.Core.Infrastructure.Constants
{
  public  class GlobalConstants
    {
        public const int TotalNumbersOfPlayers = 11;
        public const int TotalNumberGroups = 4;

        public const int PlayerNumberMin = 1;
        public const int PlayerNumberMax = 50;

        public const int CapabilityMinInPercents = 60;
        public const int CapabilityMaxInPercents = 100;

        public const int CoachCapabilityMinInPercents = 80;
        public const int CoachCapabilityMaxInPercents = 100;

        public const int PlayerAgeMin = 18;
        public const int PlayerAgeMax = 45;

        public const int CoachAgeMin = 30;
        public const int CoachAgeMax = 65;

        public const int WeigthMin = 50;
        public const int WeigthMax = 110;

        public const int HeigthMin = 150;
        public const int HeigthMax = 200;
        public readonly static  IList<string> TeamNames = new List<string> {
        "Albania",
        "Andorra",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "England",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Gerogia",
        "Germany",
        "Gibraltar",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Israel",
        "Italy",
        "Kazakhstan",
        "Kosovo",
        "Latvia",
        "Leichtenstein",
        "Lithuania",
        "Luxemburg",
        "Macedonia",
        "Malta",
        "Moldova",
        "Montenegro",
        "Netherlands",
        "Northern Ireland",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "SanMarino",
        "Scotland",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Turkey",
        "Ukraine",
        "Wales"
            };
        public readonly static IList<string> FirstNames = new List<string>  {
            "Jackson",
            "Aiden",
            "Liam ",
            "Lucas",
            "Noah ",
            "Mason",
            "Jayden",
            "Ethan",
            "Jacob",
            "Jack",
            "Caden",
            "Logan",
            "Benjamin",
            "Michael",
            "Caleb",
            "Ryan",
            "Alexander",
            "Elijah",
            "James",
            "William",
            "Oliver",
            "Connor",
            "Matthew",
            "Daniel",
            "Luke",
            "Brayden",
            "Jayce",
            "Henry",
            "Carter",
            "Dylan",
            "Gabriel",
            "Joshua",
            "Nicholas",
            "Isaac",
            "Owen",
            "Nathan",
            "Grayson",
            "Eli",
            "Landon",
            "Andrew",
            "Max",
            "Samuel",
            "Gavin",
            "Wyatt",
            "Christian",
            "Hunter",
            "Cameron",
            "Evan",
            "Charlie",
            "David",
            "Sebastian",
            "Joseph",
            "Dominic",
            "Anthony",
            "Colton",
            "John",
            "Tyler",
            "Zachary",
            "Thomas",
            "Julian",
            "Levi",
            "Adam",
            "Isaiah",
            "Alex",
            "Aaron",
            "Parker",
            "Cooper",
            "Miles",
            "Chase",
            "Muhammad",
            "Christopher",
            "Blake",
            "Austin",
            "Jordan",
            "Leo",
            "Jonathan",
            "Adrian",
            "Colin",
            "Hudson",
            "Ian",
            "Xavier",
            "Camden",
            "Tristan",
            "Carson",
            "Jason",
            "Nolan",
            "Riley",
            "Lincoln",
            "Brody",
            "Bentley",
            "Nathaniel",
            "Josiah",
            "Declan",
            "Jake",
            "Asher",
            "Jeremiah",
            "Cole",
            "Mateo",
            "Micah",
            "Elliot" };

        public readonly static IList<string> LastNames = new List<string>
        {
           "Messi",
           "Ronaldo",
           "Iniesta",
           "Ibrahimovic",
           "Falcao",
           "van Persie ",
           "Pirlo",
           "Toure",
           "Cavani",
           "Aguero",
           "Casillas",
           "Busquets",
           "Alonso",
           "Silva",
           "Ozil",
           "Silva",
           "Schweinsteiger",
           "Buffon",
           "Suarez",
           "Ramos",
           "Kompany",
           "Pique",
           "Lahm",
           "Reus",
           "Ribery",
           "Neuer",
           "Cole",
           "Rooney",
           "Mata",
           "Muller",
           "Götze",
           "Benzema",
           "Fabregas",
           "Mascherano",
           "Bale",
           "Zanetti",
           "De Rossi",
           "Alves",
           "Cech",
           "Hummels",
           "Puyol",
           "Di Maria",
           "Tevez",
           "Drogba",
           "Chiellini",
           "Defender",
           "El Shaarawy",
           "Kroos",
           "Eto’o",
           "Alba",
           "Gomez",
           "Vidal",
           "Hazard",
           "Rodriguez",
           "Fellaini",
           "Villa",
           "Jan Huntelaar",
           "Vidic",
           "Hart",
           "Robben",
           "Balotelli",
           "Valbuena",
           "Aubameyang",
           "Lewandowski",
           "Cazorla",
           "Eriksen",
           "Lavezzi",
           "Moutinho",
           "Mandžukić",
           "Evra",
           "Luiz",
           "Modric",
           "Wanyama",
           "Yanga - M’Biwa",
           "Srna",
           "Mayuka",
           "Terry",
           "Asamoah",
           "Bonucci",
           "Pastore",
           "Mkhitaryan",
           "Dembele",
           "Ben Arfa",
           "Nasri",
           "Kagawa",
           "Sneijder",
           "Defender",
           "Hamsik",
           "Martinez",
           "Forlan"
      };
    }
}
